[package]
name = "oripop-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
rand.workspace = true
serde.workspace = true
winit.workspace = true

[dev-dependencies]
serde_json.workspace = true
